# Generated by Django 4.2.2 on 2023-09-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200, unique=True)),
                ('phone_no', models.TextField(max_length=40)),
                ('password', models.TextField(max_length=200)),
                ('c_password', models.TextField(max_length=200)),
            ],
        ),
    ]
