# Generated by Django 4.2.2 on 2023-09-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_tlb_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_orders', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.fooditem')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.tlb_order')),
            ],
        ),
    ]
