# Generated by Django 4.2.2 on 2023-09-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0006_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('remarks', models.TextField(max_length=200)),
                ('date_recorded', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.fooditem')),
            ],
        ),
    ]
