# Generated by Django 4.2.2 on 2023-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0008_remove_tlb_order_process_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_rating',
            name='score',
        ),
        migrations.AddField(
            model_name='tbl_rating',
            name='sentiment',
            field=models.TextField(default='', max_length=20),
        ),
    ]
