# Generated by Django 4.2.2 on 2023-10-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0009_remove_tbl_rating_score_tbl_rating_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_rating',
            old_name='customer',
            new_name='customer_name',
        ),
    ]
